# version: "3.8"

networks:
    sauliai-network:
        name: sauliai-network

services:
    signal-server:
        image: sauliai/signal-server:latest
        container_name: signal-server
        build:
            context: ./
            dockerfile: .docker/signal-server/local/Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./.m2/:/root/.m2
        environment:
            BASEDIR: /var/www/html
            HOME: /var/www/html
        #    MAVEN_CONFIG: /var/www/html/.m2
        #      SYSTEM_UID: '${SYSTEM_UID}'
        #      SYSTEM_GID: '${SYSTEM_GID}'
        # user: ${CURRENT_UID}
        ports:
             - "8080:8080"
             - "8081:8081"

        networks:
            - sauliai-network

        depends_on:
#            - signal-db
            - cache

    signal-db:
        container_name: signal-db
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - ./db/:/var/lib/postgresql/data/
#            - ./db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
            - ./db-shared:/db-shared
#            - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
        networks:
            - sauliai-network
    cache:
        image: redis:7.4.2
#        container_name: cache
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass Labas123
        volumes:
            - cache:/data
        networks:
            - sauliai-network
volumes:
    cache:
        driver: local

    db:
        driver: local


