FROM maven:3.8.6-openjdk-11

# this is for keeping container running
# ENTRYPOINT ["tail", "-f", "/dev/null"]

WORKDIR /var/www/html

#EXPOSE 9000

# ENV MAVEN_CONFIG=/var/www/html/.m2

#ENTRYPOINT [ "mvn", "quarkus:dev", "-DdebugHost=0.0.0.0"]

ENTRYPOINT [ "sleep",  "infinity" ]

